name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        uses: actions/checkout@v2
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag blog-app-backend:$(date +%s)
      - name: Push Docker image to hub
        run: docker push isnakolah/blog-app-api-server:blog-app-backend:$(date +%s)
